#ifndef SLAM_FACTORY_VERSION_H
#define SLAM_FACTORY_VERSION_H

#define SF_VERSION_MAJOR    0
#define SF_VERSION_MINOR    0
#define SF_VERSION_REVISION 0
#define SF_VERSION_STATUS   ""

#define SFAUX_STR(__A)      #__A

#define SFAUX_STRW(__A)     L ## #__A

#define SF_VERSION          SFAUX_STR(SF_VERSION_MAJOR) "." SFAUX_STR(SF_VERSION_MINOR) "." SFAUX_STR(SF_VERSION_REVISION) SF_VERSION_STATUS

#endif